db_settings:
  host: ""
  database: ""
  user: ""
  password: ""
dof_decoding:
  action:
    A: "Add"
    C: "Change"
  lighting:
    R: "Red"
    D: "Medium intensity White Strobe & Red"
    H: "High Intensity White Strobe & Red"
    M: "Medium Intensity White Strobe"
    S: "High Intensity White Strobe"
    F: "Flood"
    C: "Dual Medium Catenary"
    W: "Synchronized Red Lighting"
    L: "Lighted (Type Unknown)"
    N: "None"
    U: "Unknown"
  marking:
    P: "Orange or Orange and White Paint"
    W: "White Paint Only"
    M: "Marked"
    F: "Flag Marker"
    S: "Spherical Marker"
    N: "None"
    U: "Unknown"
  hor_acc:
    "1": "20ft"
    "2": "50ft"
    "3": "100ft"
    "4": "250ft"
    "5": "500ft"
    "6": "1000ft"
    "7": "0.5NM"
    "8": "1NM"
    "9": "Unknown"
  vert_acc:
    A: "3ft"
    B: "10ft"
    C: "20ft"
    D: "50ft"
    E: "125ft"
    F: "250ft"
    G: "500ft"
    H: "1000ft"
    I: "Unknown"
