# Specify which special parallels to generate
parallels:
    north_polar_circle: true
    south_polar_circle: false
    tropic_cancer: true
    tropic_capricorn: false
# Path to the output file with generated parallels
output: "special_parallels_140W_90W.gpkg"
# Specify longitude range for generated parallels
longitudes:
    start: -140
    end: -90
